#:schema https://raw.githubusercontent.com/YunoHost/apps/main/schemas/manifest.v2.schema.json

packaging_format = 2

id = "docs"
name = "Docs"
description.en = "Collaborate and write in real time, with no layout constraints"
description.fr = "Collaborer et écrire en temps réel, sans contrainte de mise en page"

version = "3.4.0~ynh2"

maintainers = ["fflorent", "Ddataa", "mjeammet", "Flightan"]

[upstream]
license = "MIT"
website = "https://docs.numerique.gouv.fr"
demo = "https://docs.numerique.gouv.fr"
code = "https://github.com/suitenumerique/docs/"

[integration]
yunohost = ">= 12.0.9"
helpers_version = "2.1"
architectures = ["amd64", "arm64", "armhf"]
multi_instance = true

ldap = false
sso = true

# FIXME: replace with an **estimate** minimum disk and RAM requirements. e.g. 20M, 400M, 1G...
disk = "50M"
ram.build = "50M"
ram.runtime = "50M"

[install]
    [install.dex]
    type = "app"
    filter = "match(id, '^(dex)(__[0-9+])?$')"
    ask.en = "Select the Dex app that will handle authentication."
    ask.fr = "Sélectionnez l'app Dex qui gérera l'authentification."
    help.en = "You need to have at least one instance of Dex installed beforehand on your server."
    help.fr = "Vous devez avoir au moins une instance de Dex préalablement installée sur votre serveur."

    [install.s3]
    type = "app"
    filter = "match(id, '^(minio|garage)(__[0-9+])?$')"
    ask.en = "Select the S3 app (Garage or Minio) that will handle storage."
    ask.fr = "Sélectionnez l'app S3 (Garage ou Minio) qui gérera le stockage."
    help.en = "You need to have at least one instance of Garage or Minio installed beforehand on your server."
    help.fr = "Vous devez avoir au moins une instance de Garage ou Minio préalablement installée sur votre serveur."

    [install.domain]
    type = "domain"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

    [install.language]
    ask.en = "Choose the application language"
    ask.fr = "Choisissez la langue de l'application"
    type = "select"
    choices = ["en-us", "fr-fr", "de-de", "nl-nl", "es-es"]
    default = "en-us"

    [install.enable_celery]
    ask.en = "Do you want to enable celery?"
    ask.fr = "Voulez-vous activer celery ?"
    type = "boolean"
    optional = true
    help.en = "This unlocks some features – like email sending – but at the expense of increased RAM usage."
    help.fr = "Cela déverrouille quelques fonctionnalités, telles que l'envoi de mails, mais au prix d'une consommation de RAM accrue."


[resources]
    [resources.sources]

    [resources.sources.main]
    url = "https://github.com/suitenumerique/docs/archive/refs/tags/v3.4.0.tar.gz"
    sha256 = "347df88da873b2b717cc052378be7fa4cec64a246400dc093bdf96fd8f89b878"
    autoupdate.strategy = "latest_github_tag"

    [resources.system_user]
    allow_email = true

    [resources.install_dir]

    [resources.permissions]
    main.url = "/"

    [resources.ports]
    backend.default = 8000
    yprovider.default = 4444

    [resources.apt]
    packages = "redis, python3, python3-venv, python3-setuptools, python3-pip, postgresql, rdfind, gettext"
    extras.yarn.repo = "deb https://dl.yarnpkg.com/debian/ stable main"
    extras.yarn.key = "https://dl.yarnpkg.com/debian/pubkey.gpg"
    extras.yarn.packages = "yarn"

    [resources.database]
    type = "postgresql"
